window.SHINO_EPISODES=window.SHINO_EPISODES||{};
window.SHINO_EPISODES["ep006"]={
  "id":"ep006",
  "number":6,
  "title":"この感じを持っていく",
  "description":"何も起きないまま。",
  "ending":"誰にも見えないけど、確かにここにある。",
  "story":[
    {
      "type":"narration",
      "text":"朝、ミオは少し早く目を覚ました。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"目覚ましよりも前。\n理由はない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"窓を開けると、空はまだ薄い色をしている。\n昨日と同じはずなのに、\nどこか違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、それを確認しない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"机の上に、小さなバッグが置いてある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"中には、\n着替えと、ノートと、\n使い切りかけのペン。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"特別なものは入っていない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「忘れ物ない？」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"母がキッチンから声をかける。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「たぶん、ない」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"学校へは行かない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"今日は、行かない日だ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"理由は説明できるけど、\n説明しない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは町を歩く。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"校門の前を通り過ぎる。\n誰かが走り込んでいく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"給水塔の方へ、最後に寄る。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"フェンスは相変わらず壊れたまま。\n草も、影も、同じ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは立ち止まる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ここで、\n何かが起きたことは一度もない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"でも、\nここで何も起きなかった時間が、\n確かにあった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、深く息を吸う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"跳ねる前の、この感じ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"今日は、少しだけ形が違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"駅へ向かう道。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ユウトが、自転車で通り過ぎる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「あ！」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「どこ行くんだ？」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「まだ決まってない」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「そっか。いいな」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"それで十分だった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ホームに立つ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"電車が来る音がする。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"人は少ない。\n誰も急いでいない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、バッグの紐を握る。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"胸の奥に、\nあの感覚がある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"でも今日は、\n起きる前でも、起きなかった後でもない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"持っていく感じだ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"電車が止まる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ドアが開く。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ミオは、一歩踏み出す。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"跳ねない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"でも、戻らない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"席に座って、窓の外を見る。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"町が、少しずつ遠ざかる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ミオは思う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"跳ねなくても、\n進める場所はある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"名前をつけなくても、\n持っていけるものがある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"この感じ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"ending",
      "text":"誰にも見えないけど、\n確かにここにある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43",
      "clear":true,
      "fontSize":"xl",
      "disappearAfter":4200,
      "disappearFade":1800
    }
  ]
};
