window.SHINO_EPISODES=window.SHINO_EPISODES||{};
window.SHINO_EPISODES["ep005"]={
  "id":"ep005",
  "number":5,
  "title":"誰かが跳ねる",
  "description":"友だちが突然動き出す。",
  "ending":"それでいい。",
  "story":[
    {
      "type":"narration",
      "text":"その日は、朝から少しだけ違っていた。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"音が多いわけでも、\n空が明るいわけでもない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"でも、\n誰かがもう決めてしまっている感じがした。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"休み時間。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"教室の後ろで、ユウトが立っている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"机に座らない。\n友だちとも話さない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ただ、窓の外を見ている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、それに気づく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"給水塔の裏で感じる“前”とは、\n少し違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"これは――\nもう、向こう側に傾いている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"昼休み。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「俺さ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「放課後、部活やめる」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、驚かない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「そっか」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「急だよな」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ユウトは、少し笑う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「でも、今しかない気がしてさ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"理由は言わない。\n説明もしない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"でも、その言い方で分かる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"もう跳ねている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"放課後。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"校庭の隅で、ユウトが先生と話している。\nミオは遠くから見ている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"声は聞こえない。\n表情もよく分からない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"でも、\nユウトの背中が、\n少し軽くなっている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、それ以上近づかない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夕方。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"給水塔の裏。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、いつもの場所にいる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"今日は、\nここに“前”はない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"張りつめも、静けさも、\nどこか違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"代わりに、\n誰かが通り過ぎた後の空気が残っている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ミオは思う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ああ、\n今日はここじゃなかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"帰り道。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「ミオ！」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"少し息が切れているけど、\n顔は明るい。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「決めた」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「怖いけどさ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"それ以上、言わない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ユウトは一瞬、何か言いかけて、\nやめる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「じゃあな！」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"そう言って、走っていく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは立ち止まる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夕焼けが、昨日より少し濃い。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"胸の奥に、\n見慣れた感覚がある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"でも今日は――\n自分のじゃない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、それを受け取らない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ただ、\nちゃんと見送る。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夜。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ベッドに横になって、\nミオは考える。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"跳ねる人がいる。\n跳ねない人もいる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"どっちが正しいとか、\n早いとか、遅いとかじゃない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ただ、\n順番と場所が違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは目を閉じる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"ending",
      "text":"自分の中には、\nまだ“前”がある。\n\nそれでいい。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43",
      "clear":true,
      "fontSize":"xl",
      "disappearAfter":4200,
      "disappearFade":1800
    }
  ]
};
