window.SHINO_EPISODES=window.SHINO_EPISODES||{};
window.SHINO_EPISODES["ep004"]={
  "id":"ep004",
  "number":4,
  "title":"跳ねなかった日",
  "description":"何も起きない一日にも、形は残る。",
  "ending":"それも、通り過ぎていく。",
  "story":[
    {
      "type":"narration",
      "text":"朝、目覚ましは鳴った。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオはすぐに起きた。\n遅れてはいないし、早すぎもしない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"窓の外は、曇り。\n雨が降りそうで、降らない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"その感じが、今日に合っている気がした。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"学校へ行く道で、猫を見かけた。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"いつも同じ場所にいる、白と茶色の猫。\n今日は、まるくなって動かない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは少しだけ立ち止まる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"猫は目を開けるけど、立ち上がらない。\nミオも、声をかけない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"二人とも、動かないまま。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"しばらくして、ミオは歩き出す。\n猫は、そのまま。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"授業は、全部いつも通りだった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"黒板の字。\nノートを取る音。\nページをめくる音。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ユウトが小さくあくびをする。\n先生が一度だけ注意する。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"誰も笑わないし、\n誰も怒らない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、時計を一度も見なかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"昼休み。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"校庭では、ボールが跳ねている。\n声も跳ねている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオはベンチに座る。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"今日は、参加しない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"理由はない。\n誘われもしなかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"風が吹いて、\n木の葉が一枚、落ちる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"それだけ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"放課後。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"給水塔の裏に行く。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"いつもと同じ場所。\n同じフェンス。\n同じ草。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"でも今日は、\n何も起きそうな気配すらない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"張りつめてもいない。\n期待も、ためらいもない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ただ、静か。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオはそこに座って、\nしばらく目を閉じる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"何かを待つ気は、なかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"帰り道、ユウトとすれ違う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「今日さ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「なんもなかったな」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオはうなずく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん。なかった」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"それは残念でも、\nつまらなくもなかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夜。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"部屋の明かりを消して、\nベッドに横になる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"一日を思い返す。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"猫。\n曇り空。\n授業。\n風。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"どれも、\n跳ねなかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"でも、\n一日が消えた感じはしない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ちゃんと、ここにある。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは思う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"跳ねない日は、\n空っぽじゃない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ただ、\nそのままなだけだ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"目を閉じる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"ending",
      "text":"外で、遠くの電車の音がする。\n\nそれも、通り過ぎていく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43",
      "clear":true,
      "fontSize":"xl",
      "disappearAfter":4200,
      "disappearFade":1800
    }
  ]
};
