window.SHINO_EPISODES=window.SHINO_EPISODES||{};
window.SHINO_EPISODES["ep003"]={
  "id":"ep003",
  "number":3,
  "title":"名前をつけない",
  "description":"名前をつけると消える気がする。",
  "ending":"つけない。まだ。",
  "story":[
    {
      "type":"narration",
      "text":"理科室の黒板には、今日のテーマが書いてあった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「現象に名前をつける」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"先生はチョークを置いて言う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「名前があると、説明しやすくなる。\n説明できると、理解した気になる」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"何人かがうなずく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「でも」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「名前をつけた瞬間に、\n見えなくなる部分もある」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、その言葉にだけ反応する。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ノートは開いているけど、\n何も書かない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"放課後、ユウトが言った。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「今日の理科さ、ちょっと難しくなかった？」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「うん」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「名前つけないと始まらないって感じでさ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、少しだけ考えてから言う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「つけないままでも、始まってることもある」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"ユウトは笑う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「それ、テストで使えないやつだろ」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオも、少し笑う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"給水塔の裏。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"今日は、いつもより長くいる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"風が止まったり、\nまた吹いたりする。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、それを数えない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"もし数えたら、\n何かが決まってしまう気がしたから。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"足元の草の間に、\n小さな虫がいる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"動いたり、止まったり。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、名前を思い出そうとして、やめる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"虫の名前。\nこの場所の名前。\nこの感じの名前。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"どれも、今は要らなかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"家に帰ると、母が聞く。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「今日、学校どうだった？」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは少し迷ってから答える。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"「ふつう」",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"それ以上は言わない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"母はそれ以上聞かない。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夕飯の音がする。\nテレビのニュースが流れる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"画面の中では、\n何かに名前がつけられて、\n説明されて、\n区切られていく。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは、音だけを聞いている。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"夜。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ベッドに入って、目を閉じる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"昼の給水塔の裏を思い出す。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"あそこには、\n説明も、判断も、なかった。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ただ、起きそうで、起きない感じ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"ミオは思う。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"narration",
      "text":"名前をつけたら、\nそれはもう、終わったものになる。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"dialogue",
      "text":"だから、自分は――",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43"
    },
    {
      "type":"ending",
      "text":"つけない。\n\nまだ。",
      "pause":1900,
      "view":"world",
      "effect":"fade",
      "textColor":"custom",
      "customColor":"#4f4a43",
      "clear":true,
      "fontSize":"xl",
      "disappearAfter":4200,
      "disappearFade":1800
    }
  ]
};
